### ISSUE TITLE
`Toggle`を再実装する

### ISSUE THREAD

**Issue by dino3616** [3I-shikosai32/shikosai32-front#159]

**Comment by ReoHakase** [comment]
どこを変えてほしいの？👀

**Comment by dino3616** [comment]
アホすぎた。
なぜdescriptionを書いていないのか。

- sizeが3パターンに限定されてるのは汎用性に欠けるくない？
- colorはtailwindのclassとしてのstring...？だとしたら今のままだと補完効かないからダメじゃね？

**Comment by ReoHakase** [comment]
解決策の一つとしては、
- classNameを公開
- スタイルはユーティリティクラスの指定で上書きする
- aspect-ratioで縦横比固定
かな？
型補完はしらべないとわかんない
