### ISSUE TITLE
Buttonの作成

### ISSUE THREAD

**Issue by dino3616** [3I-shikosai32/shikosai32-front#17]
## Support

```ts
type Props = {
  text: string;
  icon?: string;
  className?: string;  // bg-color指定用
}

const Button: FC<Props> = ({text, icon}) => {}
```

## Reference Documents

- https://www.figma.com/file/sfwYU5BKtdxAPxaE9ciAi7/OZ?node-id=78%3A681

**Comment by ReoHakase** [comment]
- [ ] コンポーネントのドキュメントを書く
- [ ] スタイルの優先順位問題を解決する
