### ISSUE TITLE
各ページの`<title>`の文字列の書式を統一する

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/shikosai32-front#216]
タイトル命名のルールを決めてなかったから混沌としてますね😥
`<Layout title="loading... | OZ">`
`<Layout title="500 | Internal Server Error">`
`<Layout title="OZ | Xeno">`

**Comment by dino3616** [comment]
以下のルールを提案します。

- `index`に限り、`OZ | ちょっとした説明` or `OZ`とする
- それ以外は`page-name | OZ`または`loading... | OZ`とする
  - 500エラーページの場合、`Internal Server Error | OZ`とする

**Comment by ReoHakase** [comment]
賛成です！
今あるPRがすべてマージされ次第修正します。
