### ISSUE TITLE
コンポーネントのPropsとして受け取ったTailwindのユーティリティクラスを、優先して適用させられるようにする

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/shikosai32-front#33]
# 現状
#17 のようなコンポーネントにデフォルトのスタイルを設定しつつ、`background-color`などを含めたスタイルを外部から変更できるようにしたい場合に必要となる。
このとき、TailwindCSSを使用しているため、「`className`を`Props`として受け取り自身のクラス指定に追加する」といった実装となる。
しかし、Tailwindは下記のように、ユーティリティクラス名のみでスタイルを指定するため、すべてのスタイルが同じ詳細度を持つ。したがって、**その優先順位は記述されたCSSがより後に読み込まれたものが優先される**。
```css
.text-neutral-900 {
  --tw-text-opacity: 1;
  color: rgb(8 15 22 / var(--tw-text-opacity));
}
```
[CodePenでCSSの動作を確かめる](https://codepen.io/ReoHakase/pen/VwxYjRW)

# 考えられる対応策
参考 [[Feature Proposal] CSS class override utility for component composition.
#1446](https://github.com/tailwindlabs/tailwindcss/discussions/1446)
## その1: `!important` でデフォルトのものを上書きする
使うべきではないと思う
```tsx
<Button className="!bg-success-700">
  Hello world!
</Button>
```
## ~~その2: [`:where()`疑似クラス](https://developer.mozilla.org/ja/docs/Web/CSS/:where)を使ってデフォルトのスタイルの詳細度を０にしておく~~
`where:bg-***`のようにTailwindのVariantとして使えるようにプラグインを書く。
使う側は、その１とは違い`!important`をつけるなどの配慮をしなくてよい。

### 追記
[Insane idea to give components *overridable* default TW classes #3523](https://github.com/tailwindlabs/tailwindcss/discussions/3523)
```js
// 詳細度を0に設定する擬似クラス:where()をバリアントとして追加する
    plugin(({ addVariant, e: escape }) => {
      addVariant('where', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `:where(.${escape(`where${separator}${className}`)})`;
        });
      });
    }),
```
`:where()`で囲んだだけではリセットCSSにも勝てないくそざこなめくじになってしまいデフォルトのスタイルが適用できず、
`body :where()`のようにしてTailwindのユーテリティクラス以下リセットCSS以上の詳細度を適用しようとしても、必要な詳細度の基準がリセットCSSの定義によって変わってしまうから扱いづらい。ので`:where()`で詳細度を下げるのは現実的ではないと思いました

### ~~`tailwind-override`~~
~~[参考: Zenn.dev](https://zenn.dev/tosssy/articles/ad479f871591da)~~
~~- `.tailwind.config.js`を読み取ってカスタムクラスまで対応してくれるのかが不明~~
~~- CSSの詳細度の問題をJS/TS側で無理やり対処しているところがすっきりしない~~
~~- GitHubのスター数が84で頼りない~~
### `tailwind-merge`
```tsx
import { twMerge } from 'tailwind-merge'

twMerge('px-2 py-1 bg-red hover:bg-dark-red', 'p-3 bg-[#B91C1C]')
// → 'hover:bg-dark-red p-3 bg-[#B91C1C]'
```
クラス名に対立(Conflict)する複数のTailwindユーティリティクラスが存在する場合、後ろのものを優先して抜き出してくれる関数`twMerge`を提供するパッケージ。
- キャッシュと遅延計算でパフォーマンスが考慮されている
> Optimized for speed
> Results get cached by default, so you don't need to worry about wasteful re-renders. The library uses a [LRU cache](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) which stores up to 500 different results. > The cache size can be modified or opt-out of by using [extendTailwindMerge](https://github.com/dcastil/tailwind-merge/blob/v1.6.0/docs/api-reference.md#extendtailwindmerge).
> Expensive computations happen upfront so that twMerge calls without a cache hit stay fast.
> These computations are called lazily on the first call to twMerge to prevent it from impacting app startup performance if it isn't used initially.
- コンフィグを設定すれば`.tailwind.config.js`に記述した`gradient-*`などの独自のクラスにも対応できる
- GitHubスター数563と多め
- 直近コミットが16日前

## その4: [カスタムクラス](https://tailwindcss.com/docs/adding-custom-styles)を`@layer components`で作成する
![image](https://user-images.githubusercontent.com/16751535/188320899-94667529-cc22-42a6-b77f-ee3b84edf880.png)
Tailwindはここで定義されたものを含む`components`クラスを`bg-red-500`等のユーティリティクラスよりも前に挿入するから、それを使用したスタイルの上書きが適切に行えるようになる。しかし、多階層の上書きはできない

**Comment by dino3616** [comment]
`Props.className`で`font-semibold`を指定したとき、

- コンポーネントの定義を優先する場合

```tsx
{/* font-boldが優先される */}
<div className={`${className} font-bold`}>
```

- `Props.className`を優先する場合

```tsx
{/* font-semiboldが優先される */}
<div className={`font-bold ${className}`}>
```

の二つの選択肢があるけど、でもどっちにしろコンポーネントの定義見ないと使用者は予期せぬ動作を引き起こしてしまうからどうにかしないとヤバくね？

って話で合ってる？

**Comment by ReoHakase** [comment]
それも大事じゃないわけではないけど、自分が今回issueを立てた理由は、
Tailwindが出力したCSSコードの中で、コンポーネント内部で指定した`.bg-neutral-900`が外部から指定した`.bg-success-700`よりもあとに来てしまうと、`${className}`の挿入箇所に関わらずスタイルが上書きできなかったから↓
![image](https://user-images.githubusercontent.com/16751535/188317450-753daa0d-ec02-4185-9b34-2dfe1b8038c8.png)
![image](https://user-images.githubusercontent.com/16751535/188317465-0a2eb1b7-3447-4f02-a06e-40c3e12ad813.png)
だからコード上で明確に優先順位を指定できるようにしなければいけないんだけど、それをどうやって実現するのか考えてる

**Comment by dino3616** [comment]
あー普段の実装では気にしてなかったけど、StoryBookで起こった問題かこれ

**Comment by ReoHakase** [comment]
![image](https://user-images.githubusercontent.com/16751535/188318097-99332a4a-3dc0-4aaf-9675-228e6b8859be.png)
```tsx
import type { FC } from 'react';
import { MdAccessibilityNew } from 'react-icons/md';
import { Button, ButtonIcon } from '@/components/Button';

const Index: FC = () => (
  <main className="flex min-h-screen w-screen items-center justify-center">
    <div className="rounded-3xl bg-gradient-to-br p-8 gradient-primary">
      <h1 className="font-branding text-4xl font-bold text-white">Hello OZ at 茨城高専</h1>
      <Button className="bg-success-700" type="button">
        <ButtonIcon>
          <MdAccessibilityNew />
        </ButtonIcon>
        <i>react-icon</i>を使ったボタン
      </Button>
    </div>
  </main>
);

export default Index;
```
CSSの詳細度に依る問題だから、やっぱりStorybookの外でも同様だった

**Comment by dino3616** [comment]
> したがって、その優先順位は記述されたCSSがより後に読み込まれたものが優先される。

理解力が足りてなくて申し訳ないが、つまりどうあがいてもコンポーネントの定義のclassNameが優先されるってこと？

**Comment by ReoHakase** [comment]
そうなんだよねえ
TailwindがJITで吐き出す順によるから、運良く外部指定のクラスが後に来た時は上書きができる...んだよね、実はさっきまで適切に上書きできてたし

**Comment by dino3616** [comment]
ひとつごり押し解決策を思いついた。

1. 予めコンポーネントで使う`className`を`const className = `で定義しておく。(例: `const className = "flex"`)
2. `props.className`に`className`と競合するスタイルがないかを調べる。
3. `className`と`props.className`をmergeする。

**Comment by dino3616** [comment]
うーん、やっぱ至難の業すぎるのでこれはダメだな。

**Comment by ReoHakase** [comment]
> ## その3: [`tailwind-override`](https://github.com/richardgill/tailwind-override)を`className`内で使う
> [参考: Zenn.dev](https://zenn.dev/tosssy/articles/ad479f871591da)
> - `.tailwind.config.js`を読み取ってカスタムクラスまで対応してくれるのかが不明
> - CSSの詳細度の問題をJS/TS側で無理やり対処しているところがすっきりしない
> - GitHubのスター数が84で頼りない

これがその案とほぼ同じことをやってるけど、結局`props`を受け渡すたびにコンフリクトがないかどうか計算してるからパフォーマンス的にあまりよくない _(要検証)_ と思う

**Comment by dino3616** [comment]
それを使う or 例えばカラーを外から指定したいだけであれば、`color: "red"|"green"|string`みたいなPropsを定義して、`bg-${color}`をすればいい。
パフォーマンスについてはそれほど気にしなくても~~いい~~わけではないけど、まぁそれくらいなら...。

**Comment by dino3616** [comment]
(これを言ってしまうと元も子もないけど、ここまで来ると多分外部から`className`で指定すること自体アンチパターンな気がする...)

**Comment by ReoHakase** [comment]
> ### `tailwind-merge`
> ```tsx
> import { twMerge } from 'tailwind-merge'
> 
> twMerge('px-2 py-1 bg-red hover:bg-dark-red', 'p-3 bg-[#B91C1C]')
> // → 'hover:bg-dark-red p-3 bg-[#B91C1C]'
> ```
> クラス名に対立(Conflict)する複数のTailwindユーティリティクラスが存在する場合、後ろのものを優先して抜き出してくれる関数`twMerge`を提供するパッケージ。
> - キャッシュと遅延計算でパフォーマンスが考慮されている
> > Optimized for speed
> > Results get cached by default, so you don't need to worry about wasteful re-renders. The library uses a [LRU cache](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) which stores up to 500 different results. > The cache size can be modified or opt-out of by using [extendTailwindMerge](https://github.com/dcastil/tailwind-merge/blob/v1.6.0/docs/api-reference.md#extendtailwindmerge).
> > Expensive computations happen upfront so that twMerge calls without a cache hit stay fast.
> > These computations are called lazily on the first call to twMerge to prevent it from impacting app startup performance if it isn't used initially.
> - コンフィグを設定すれば`.tailwind.config.js`に記述した`gradient-*`などの独自のクラスにも対応できる
> - GitHubスター数563と多め
> - 直近コミットが16日前

これで解決する方向性でいいかな？
