### ISSUE TITLE
GraphQLのスキーマ由来の型を`gql-codegen`で生成するために、適当な`.gql`ファイルを作成する

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/shikosai32-front#64]

**Comment by dino3616** [comment]
ひとつだけ注意事項です。
現段階のサーバーでIntrospectionされているSchemaは、まだ完全なものではなく修正される可能性しかないことにだけ留意して作業してください🙏

**Comment by ReoHakase** [comment]
> ひとつだけ注意事項です。 現段階のサーバーでIntrospectionされているSchemaは、まだ完全なものではなく修正される可能性しかないことにだけ留意して作業してください🙏

了解です
