### ISSUE TITLE
`dayjs`と`date-fns`がプロジェクト内で併用されているので、どちらかに統一する

### ISSUE THREAD

**Issue by dino3616** [3I-shikosai32/shikosai32-front#88]
どっちにするかはアサイニーに任せます。
個人的にはTSで開発をしている`date-fns`の方が良さそうだなと思った。

**Comment by ReoHakase** [comment]
同様の理由から`date-fns`と`date-fns-tz`を導入したので、そちらを採用したいと思います
(実は`dayjs`がすでに入っていることに気がついていなかった)(アホ)
